DATA_DIR_PATH = '../data'
LOCK_FILE_NAME = 'last_connected.json'
GROUP_DATA_FILE_NAME = 'groups.csv'
MEMBERS_DATA_FILE_NAME = 'members.csv'
PERIODIC_FLOW_DATA_FILE_NAME = 'periodic_flows.csv'
FLOW_DATA_FILE_NAME = 'flows.csv'

NONE_STRING = 'unknown'
TRUE_STRING = 'TRUE'
FALSE_STRING = 'FALSE'
